APP__KAFKA__BROKERS=localhost:9092
app__KAFKA__GROUP_id=processing-engine
app__KAFKA__INPUT_topic=diplomas.raw_tasks
app__KAFKA__output_topic=diplomas.processing_results

APP__DATABASE__URL=postgres://gateway_user:gateway_password@localhost:5432/postgres?sslmode=disable

APP__JWT__AUTH_hmac_secret=your-secret-key-change-in-production

APP__APP__verification_base_url=http://localhost:3000/verify?payload=
APP__APP__encryption_key=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=

 # Test configuration
# Run with: cargo test --no-run-argument to needed
